### ISSUE TITLE
After yarn start error is thrown ------> "Cannot find module worker_threads"

### ISSUE THREAD

**Issue by NedimRenesalis** [tornadocash/tornado-relayer#100]
I go

```yarn start```

and get this error 

<img width="776" alt="163266168-cb43bfd4-1cbe-43dd-bb8b-0f539688ea2a" src="https://user-images.githubusercontent.com/19872990/163288663-39382228-c4f7-491e-badd-58e16ff7dd84.png">

**Comment by dan1kov** [comment]
Duplicated #98
