### ISSUE TITLE
Relayer

### ISSUE THREAD

**Issue by AndriesVanWesel** [tornadocash/tornado-relayer#16]
Hey guys, 
if I understood your telegram messages correctly this the correct next step? Well I hopefully set up a relayer correctly and its working!

Registered these domains extra for this 😀:
mainnet.relayme.eth, kovan.relayme.eth

Do you only need the ENS domains? Or is there anything more you need from me? :)
Greetings

P.S. I just read about https://github.com/tornadocash/relayer/issues/7 - is this an issue if there arent this enough ETH (0.15) on the account?

**Comment by rstormsf** [comment]
that's pretty much it! @AndriesVanWesel it seems like those URL are not hosting the relayer. Could you take a look at it again to get it up and running?

**Comment by pertsev** [comment]
Your relayer is down. Please properly setup your relayer before submitting it here. Also, make withdrawal transactions via your relayer (on both kovan and mainnet) and provide tx hashes in the comment below.

**Comment by rstormsf** [comment]
Please re-open this issue if it's still relevant.
