### ISSUE TITLE
New relayer

### ISSUE THREAD

**Issue by badpenguin42** [tornadocash/tornado-relayer#21]
I created a new relayer:

mainnet.releth.eth - Transaction: https://etherscan.io/tx/0x7a1cd7c938c32315082ecaeb471389e32d66fdfa74c7da015aede3c0a70111fb
kovan.releth.eth - Transaction: https://kovan.etherscan.io/tx/0x9037f540cf949d77210b837bc2bc7fe462c159900b36f1ee3c06e7e76715fc3e

Hope it is helpful.

**Comment by rstormsf** [comment]
@badpenguin42 Done. Plz check you TG
