### ISSUE TITLE
New relay

### ISSUE THREAD

**Issue by DefiDev930** [tornadocash/tornado-relayer#22]
I setup and tested the relay via cli and website and everything seems to be functional. 

kovan.gaasservices.eth
https://kovan.etherscan.io/tx/0x2e5104248e9ac16525c113becca7aeb6ae75743ed69b1e64fd61c22de8312f4e

mainnet.gaasservices.eth
https://etherscan.io/tx/0xa09c05dc4191042e2aad9337cd4705a8f36901c461f12d2e59b0bfda0675fd96

Let me know if anything else is needed.

**Comment by pertsev** [comment]
@DefiDev930 you were added to the list of relayers. Please provide your telegram nickname so we can add you to the channel where you can follow all the updates and news

**Comment by DefiDev930** [comment]
> @DefiDev930 you were added to the list of relayers. Please provide your telegram nickname so we can add you to the channel where you can follow all the updates and news

My telegram id is the same than on Github.
