### ISSUE TITLE
New Relay (cheap-relayer.eth)

### ISSUE THREAD

**Issue by acegilz** [tornadocash/tornado-relayer#27]
I setup and tested the relay via cli and also website and everything seems to be functional.
It will be set to only **0.03% fee**

kovan.cheap-relayer.eth
https://kovan.etherscan.io/tx/0xa6a7e3086c7e64882a481ab1b1a25cc774ac050116a2d925e5a9c34c82e9fafa

mainnet.cheap-relayer.eth
https://etherscan.io/tx/0xbf0e14d5b01c2877f3bd62cf9fb1d1324e818114e04f747d9b412d1ba8011ccd

Let me know if anything else is needed.

<img width="800" alt="Screenshot 2020-12-11 at 04 24 07" src="https://user-images.githubusercontent.com/4284362/101861891-0c5da280-3b69-11eb-9595-024fe7ef15ff.png">

**Comment by acegilz** [comment]
**updated** with mining branch, to work on the latest UI

**Comment by rstormsf** [comment]
@acegilz I apologize, we have updated instructions, from now on, you have to support goerli testnet as well.
Once you are done, please submit mainnet and goerli txs on your latest node version.

Master branch is the latest branch. 
https://github.com/tornadocash/tornado-relayer

**Comment by acegilz** [comment]
@rstormsf 
Mainnet - https://etherscan.io/tx/0xd7ad0fbd2dc9b7bcc0f23fcecf0754383544d1af811a32fdfcae6e7f55ae5ba1
Goerli - https://goerli.etherscan.io/tx/0x6090ab65381ca9476278e6a2dc8241078d502940ba45a3ced7d893d52038bf4f

**Comment by acegilz** [comment]
goerli: https://goerli.etherscan.io/tx/0xa2e23fca1f09a4fe7f91c4c63798da1cf8512ad59ff693d20fb76c037b9e8a61 (goerli.cheap-relayer.eth)

mainnet.cheap: https://etherscan.io/tx/0xbf0e14d5b01c2877f3bd62cf9fb1d1324e818114e04f747d9b412d1ba8011ccd (mainnet.cheap-relayer.eth)

**Comment by acegilz** [comment]
goerli: https://goerli.etherscan.io/tx/0xa2e23fca1f09a4fe7f91c4c63798da1cf8512ad59ff693d20fb76c037b9e8a61 (goerli-v2.cheap-relayer.eth)

mainnet: https://etherscan.io/tx/0xbf0e14d5b01c2877f3bd62cf9fb1d1324e818114e04f747d9b412d1ba8011ccd (mainnet-v2.cheap-relayer.eth)

**Comment by rstormsf** [comment]
@acegilz please provide your DNS urls as well.

**Comment by rstormsf** [comment]
Done
