### ISSUE TITLE
New Relayer (mainnet-v2.therelayer.eth)

### ISSUE THREAD

**Issue by dmcxx** [tornadocash/tornado-relayer#28]
Hey @rstormsf !
Just setup a new relayer, tested in both networks, uptime is controlled by me and funds are in place.

**mainnet-v2.therelayer.eth** - Transaction: 
https://etherscan.io/tx/0x71d40bdf8c79164eb7c6d989139b0082c43aa73026aa155abc92bbdbfdc10ae1

**goerli-v2.therelayer.eth** - Transaction: 
https://goerli.etherscan.io/tx/0xf25b1b227665bc4d73b6e040a8af13c257481039ae50695c6a40422c6d3757b6

Telegram ID: @mrdmc

Let me know if there is any other information needed.

**Comment by dmcxx** [comment]
_Updated to v2 (mining branch rolling!)_
@rstormsf @poma @pertsev

**Comment by rstormsf** [comment]
@dmcxx I apologize, we have updated instructions, from now on, you have to support goerli testnet as well.
Once you are done, please submit mainnet and goerli txs on your latest node version.

Master branch is the latest branch.
https://github.com/tornadocash/tornado-relayer

**Comment by dmcxx** [comment]
> @dmcxx I apologize, we have updated instructions, from now on, you have to support goerli testnet as well.
> Once you are done, please submit mainnet and goerli txs on your latest node version.
> 
> Master branch is the latest branch.
> https://github.com/tornadocash/tornado-relayer

@rstormsf It's done! Everything updated, OP also with txs and urls as requested.

Thanks

**Comment by dmcxx** [comment]
> @dmcxx I apologize, we have updated instructions, from now on, you have to support goerli testnet as well.
> Once you are done, please submit mainnet and goerli txs on your latest node version.
> 
> Master branch is the latest branch.
> https://github.com/tornadocash/tornado-relayer

@rstormsf It's done! Everything updated, OP also with txs and urls as requested.

Thanks

**Comment by dmcxx** [comment]
@rstormsf @poma @pertsev Team, is there anything else needed to be approved?

Thanks.
Best Regards!

**Comment by rstormsf** [comment]
@dmcxx plz check telegram
