### ISSUE TITLE
new relayer - lowcost.eth

### ISSUE THREAD

**Issue by ethermachine** [tornadocash/tornado-relayer#30]
mainnet.lowcost.eth
kovan.lowcost.eth

everything is running (tested kovan & mainnet)

kovan - https://kovan.etherscan.io/tx/0xa94619f0543d1b0dd5316035c095817447b2ed9106365917b0be12cc8fc19460
mainnet - https://etherscan.io/tx/0x4684bc52672891cbbfaff4a13f95fc720894cbf01ba3af8727e26f5cb198f7eb

**Comment by rstormsf** [comment]
@ethermachine 
Sorry for delays.

I apologize, we have updated instructions, from now on, you have to support goerli testnet as well.
Once you are done, please submit mainnet and goerli txs on your latest node version.

Master branch is the latest branch.
https://github.com/tornadocash/tornado-relayer

**Comment by ethermachine** [comment]
@rstormsf
Mainnet - https://etherscan.io/tx/0xd7ad0fbd2dc9b7bcc0f23fcecf0754383544d1af811a32fdfcae6e7f55ae5ba1
Goerli - https://goerli.etherscan.io/tx/0x6090ab65381ca9476278e6a2dc8241078d502940ba45a3ced7d893d52038bf4f

**Comment by ethermachine** [comment]
mainnet.lowcost.eth
goerli.lowcost.eth

**Comment by ethermachine** [comment]
mainnet-v2.lowcost.eth
goerli-v2.lowcost.eth

telegram @ethermachine

**Comment by ethermachine** [comment]
@rstormsf  

mainnet-v2.lowcost.eth
goerli-v2.lowcost.eth

my telegram @ethermachine

**Comment by rstormsf** [comment]
You were added to the list of relayers. Tornado UI version 853ac48
