### ISSUE TITLE
New V2 Relayer (mainnet.relayer-service.eth) 

### ISSUE THREAD

**Issue by HertzHz** [tornadocash/tornado-relayer#31]
ENS Record: `v2.hertz-relayer.eth`
Mainnet Txn: [0xa2567bb34f801b10caaf7ab45c66eb76f7479a79de2eaf02c54ecd74f23d6bd2](https://etherscan.io/tx/0xa2567bb34f801b10caaf7ab45c66eb76f7479a79de2eaf02c54ecd74f23d6bd2)

Telegram: No username, find me via `Hertz` in the group.

**Comment by rstormsf** [comment]
@HertzHz 
I apologize, we have updated instructions, from now on, you have to support goerli testnet as well.
Once you are done, please submit mainnet and goerli txs on your latest node version.

Master branch is the latest branch.
https://github.com/tornadocash/tornado-relayer

You have to have telegram username, please setup one and let us know. Thanks

**Comment by HertzHz** [comment]
Seems the branch master is broken, port 80 will be redirected to nginx and get a 404 so SSL Cert cannot be issued.

**Comment by HertzHz** [comment]
@rstormsf Done!
goerli.relayer-service.eth https://goerli.etherscan.io/tx/0x090053f0e52602e09abe842b2a9c48f32374dd30685509e9eaaf8f864975d14b
mainnet.relayer-service.eth https://etherscan.io/tx/0xa2567bb34f801b10caaf7ab45c66eb76f7479a79de2eaf02c54ecd74f23d6bd2

**Comment by HertzHz** [comment]
@HertzHzHz at telegram

**Comment by rstormsf** [comment]
@HertzHz sorry for delays. It seems like your relayer is not working anymore.

**Comment by rstormsf** [comment]
You were added to the list of relayers. Tornado UI version 853ac48
