### ISSUE TITLE
New Relayer v2 t-relay.eth

### ISSUE THREAD

**Issue by guifel** [tornadocash/tornado-relayer#32]
Hi guys,

I deployed a new relayer from the `mining` branch. Each deployment has 2 workers loaded up. 
The only things I am doing different is that my relayer is behind Cloudflare. Otherwise the configuration is pretty standard for now. 

Mainnet:
- ENS: mainnet.t-relay.eth
- URL: https://mainnet.t-relay.online
- Example transaction: https://etherscan.io/tx/0xe641010f04099ea473e702abcc8d937a706c0b8cafbf45820c74cfd29d950a6c

Goerli:
- ENS: goerli.t-relay.eth
- URL: https://goerli.t-relay.online
- Example transaction: https://goerli.etherscan.io/tx/0x0737519db5d2b272acb212ebbd8db6e4e3b0b2816a09e645d18c547f106c0577

The fee is at 0.045% and I use a TORN price twice higher. 

Telegram: @guillaumefelley

**Comment by rstormsf** [comment]
Added.
Please check telegram group
