### ISSUE TITLE
New v2 Relayer (mainnet-v2.goblin.eth)

### ISSUE THREAD

**Issue by davidqw** [tornadocash/tornado-relayer#34]
Hello guys,
    I have deployed the relayers below, apply for listing on UI, thanks

**Mainnet**

- ENS: mainnet-v2.goblin.eth
- URL: https://mainnet.polkadot.live
- Example transaction: https://etherscan.io/tx/0xa09cd896cdb9d44987cffebd3c32034dbe79d3f87026334604ecf44058b86a22

**Goerli**

- ENS: goerli-v2.goblin.eth
- URL: https://goerli.polkadot.live
- Example transaction: https://goerli.etherscan.io/tx/0x2dc159be54c4a1ead14f60f1a06d2b11b34445be72414108700833786c5288cb

Telegram: @tornado_dav

**Comment by pertsev** [comment]
You were added to the list of relayers. Tornado UI version 853ac48
