### ISSUE TITLE
New Relayer (mainnet-v2.steamer.eth) 

### ISSUE THREAD

**Issue by 1000eye** [tornadocash/tornado-relayer#35]
Hey, my telegram is Telegram: @pracandybox

**Mainnet**

- ENS: mainnet-v2.steamer.eth
- URL: https://mainnet.dfi.today
- Example transaction: https://etherscan.io/tx/0xbe62b011d09c4e9fa196499337b465cea0c72633421f51e278498883dd2f00f9

**Goerli**

- ENS: goerli-v2.steamer.eth
- URL: https://goerli.dfi.today
- Example transaction: https://goerli.etherscan.io/tx/0x2fc00abafc36d14a8a119effc3b3e485893ef1fb251238df950eb9020df0b092

**Comment by pertsev** [comment]
You were added to the list of relayers. Tornado UI version 853ac48

**Comment by pertsev** [comment]
@1000eye please check your telegram
