### ISSUE TITLE
Deployment as hidden service

### ISSUE THREAD

**Issue by DonnyPerni** [tornadocash/tornado-relayer#38]
I'm trying to test a relayer as hidden service and I found few problems:

Those two line:
https://github.com/tornadocash/tornado-relayer/blob/3a598bb7ced22c8cd36bbfcb857e32a0fbab6fb8/docker-compose.yml#L54
https://github.com/tornadocash/tornado-relayer/blob/3a598bb7ced22c8cd36bbfcb857e32a0fbab6fb8/docker-compose.yml#L57
should change `mainnet` with `server`.

It should be more clear that if you want to run it as hidden service you do not need `nginx` and `letsencrypt` (and probably `dockergen` but I'm not sure of what it does).

Moreover the web UI should not enforce `https` for `.onion`'s relayers

**Comment by poma** [comment]
Fixed

p.s. dockergen container generates dynamic configs for nginx, this is how `VIRTUAL_HOST` env var works

**Comment by DonnyPerni** [comment]
Thank you, but I think that the front end is still using https to make the connections with the .onion relayer

**Comment by poma** [comment]
Yes ui fix is in progress

**Comment by ninjavisa** [comment]
Hi @poma and @DonnyPerni  Thanks for fixing the https and .onion issue, I was wondering if there is a way to track when this change gets into mainline. I have a goerli relayer that I want to test as soon as the UI fix has been merged, thanks!

**Comment by poma** [comment]
UI fix is deployed

**Comment by ninjavisa** [comment]
@poma in which repo did you do the change? I just tried on the goerli network with my Tor node and it is not working. But I cannot tell if it my node that does not work or if I am not using your change

**Comment by ninjavisa** [comment]
![Screenshot from 2021-01-07 23-19-05](https://user-images.githubusercontent.com/76663311/103951491-c4e91880-510c-11eb-9536-0cda9be861f6.png)

**Comment by DonnyPerni** [comment]
![Screenshot_20210108_181054](https://user-images.githubusercontent.com/47698072/104044021-fb8e6400-51dc-11eb-8c46-cd0ebc1786ad.png)

It fetch the data correctly to me on TOR Browser,I guess you are using the TOR page with Brave, because I tried with that and I got the same error:

![Screenshot_20210108_181915](https://user-images.githubusercontent.com/47698072/104044995-38a72600-51de-11eb-80e1-9dd5129e0450.png)

This error is the cause of the problem:

![Screenshot_20210108_181935](https://user-images.githubusercontent.com/47698072/104045068-4eb4e680-51de-11eb-9b36-98ced7ba2fe6.png)

If I got it right it's because chromium (brave is based on that) block the http request if you are on a https website, I tried using http to connect to the app.tornado.cash and it works:

![Screenshot_20210108_182401](https://user-images.githubusercontent.com/47698072/104045551-05b16200-51df-11eb-9091-be3e194aa0a2.png)


P.S. I think that the source code of web page is not public, and I think one proposal of the new DAO could be to make the front end open-source

**Comment by ninjavisa** [comment]
Sweet it works for me too on the Tor Browser, Thanks @DonnyPerni

**Comment by poma** [comment]
The UI can also run as an .onion service, there is a description how to do that in [minified UI repo](https://github.com/tornadocash/ui-minified). But it has to be hosted by someone from the community because tornado cash team cannot run any servers for legal reasons. Although in this case there is a problem of how to verify that this hosted version is not maliciously modified. Maybe if some high profile community member hosts it and vouches with his reputation.

**Comment by acegilz** [comment]
I see this marked as resolved, however I still can't setup it as a .onion domain to work in chrome. (even forcing on http:// version)

Should this work in chrome, or only TOR?

**Comment by acegilz** [comment]
@poma I see this marked as resolved, however I still can't setup it as a .onion domain to work in chrome. (even forcing on http:// version)

Should this work in chrome, or only TOR?
