### ISSUE TITLE
New Relayer  (tornadocomes.eth)

### ISSUE THREAD

**Issue by SilasZhr** [tornadocash/tornado-relayer#40]
### goerli-v2.tornadocomes.eth
[https://goerli.etherscan.io/tx/0x67ee661abaebfe4ef8bb3f503b0cee7471c6ab7c2e7e313e6b8d0311ccd4ebc9](https://goerli.etherscan.io/tx/0x67ee661abaebfe4ef8bb3f503b0cee7471c6ab7c2e7e313e6b8d0311ccd4ebc9)

### mainnet-v2.tornadocomes.eth
[https://etherscan.io/tx/0x5a30ae09a2f219f670916d138c730d2e7fd7fff73af5ff320a30c15ee4dba2f0](https://etherscan.io/tx/0x5a30ae09a2f219f670916d138c730d2e7fd7fff73af5ff320a30c15ee4dba2f0)

### url
[tornadocomes.com](tornadocomes.com)

### tg handle
@SilasYayoi

**Comment by dan1kov** [comment]
Please follow instructions [here](https://docs.tornado.cash/general/how-to-become-a-relayer)
