### ISSUE TITLE
New Relayer (mainwxpegvryfkva.onion)

### ISSUE THREAD

**Issue by ninjavisa** [tornadocash/tornado-relayer#41]
Telegram handle: @ninjavisa

**goerli**
- 	transaction: https://goerli.etherscan.io/tx/0xf618dc022d4ccf947806960adf0b88d907479bc9d08308a7e76ee328b2f13c49
- 	url: http://goerg7hhmkss3cvz.onion/ 

**mainnet**
- 	transaction: https://etherscan.io/tx/0x45f21a9484e0d1b2eb7b9c1e3ce79ed01e3b1e6e5241eb5eaea75518a18610c0
- 	url: http://mainwxpegvryfkva.onion/

**Comment by ninjavisa** [comment]
@pertsev do I have to do anything else or just wait for the request to be approved

**Comment by ninjavisa** [comment]
@rstormsf when are you adding new relayers to the list?

**Comment by laurelgithub** [comment]
> @rstormsf when are you adding new relayers to the list?

Maybe you can get the answer from here . https://torn.community/t/upcoming-relayer-election-mechanism/28

**Comment by laurelgithub** [comment]
Maybe you can get the answer from here . https://torn.community/t/upcoming-relayer-election-mechanism/28

**Comment by rstormsf** [comment]
@laurelgithub correct. The new additions are halted until the new mechanism is implemented, proposed and executed.

**Comment by dan1kov** [comment]
Please follow instructions [here](https://docs.tornado.cash/general/how-to-become-a-relayer)
