### ISSUE TITLE
New Relayer: best-price.eth

### ISSUE THREAD

**Issue by bestprice-tornado** [tornadocash/tornado-relayer#44]
**Goerli** (goerli-v2.best-price.eth)
https://goerli.etherscan.io/tx/0x58fd444b9cfd10b4fd73cd1be8fd7a3821fd1edb1481f37379b77f28e0a93f8b

**Mainnet** (mainnet-v2.best-price.eth)
https://etherscan.io/tx/0xea6925f12a2395614b4cda67922f61de03744184fa7c8854ca49f931a9c9ba9a

Telegram: charlesyos

**Comment by bestprice-tornado** [comment]
@pertsev noticed that you have just closed this inclusion request.
Is there any problem, or will it be added soon?

**Comment by rstormsf** [comment]
@bestprice-tornado sorry about it. I will investigate and ask what happened here

**Comment by ytrezq** [comment]
@bestprice-tornado https://mainnet-v2.best-option.xyz/status down.

**Comment by dan1kov** [comment]
Please follow instructions [here](https://docs.tornado.cash/general/how-to-become-a-relayer)
