### ISSUE TITLE
New Relayer (torn-relay.eth)

### ISSUE THREAD

**Issue by davidqw** [tornadocash/tornado-relayer#45]
**mainnet-v2.torn-relay.eth** (mainnet.torn-relay.com)
https://etherscan.io/tx/0x136530f74cb0005ff7b500f057580ef8819bb0bfd0a1c35abb6d23c14ebbddbc

**goerli-v2.torn-relay.eth** (goerli.torn-relay.com)
https://goerli.etherscan.io/tx/0x142492b9689c3a54dae1f2b4abc301864df2645cee7983342b840a74bcf72d64

Telegram handle
@tornrelay

**Comment by ytrezq** [comment]
@davidqw https://mainnet.torn-relay.com/status down

**Comment by dan1kov** [comment]
Please follow instructions [here](https://docs.tornado.cash/general/how-to-become-a-relayer)
