### ISSUE TITLE
New relayer: mainnet-v2.spoperalbi.eth

### ISSUE THREAD

**Issue by spoperalbi** [tornadocash/tornado-relayer#46]
Hi guys,
My relayer is now up if you want to check it out. I can add a second worker if needed. Fee currently at 0.045%.

Goerli:
goerli-v2.spoperalbi.eth
https://goerli.etherscan.io/tx/0x67562bbe064017d66deb6be87b8694663df60b1004aa4f539c8d65ec7d485bc0

Mainnet:
mainnet-v2.spoperalbi.eth
https://etherscan.io/tx/0xf2b51bc998170053e4e157e4c29c8ca6d0a6c589223238d7cd5e8b36339ac914

My Telegram @spoperalbi

**Comment by spoperalbi** [comment]
Hi guys, any update? Are relayer applications still open?
I just updated my relayer to the latest version 4.0.8.

**Comment by ytrezq** [comment]
@spoperalbi https://mainnet.spoperalbi.xyz/status is down. So it’s normal you don’t get replies.

**Comment by dan1kov** [comment]
Please follow instructions [here](https://docs.tornado.cash/general/how-to-become-a-relayer)
