### ISSUE TITLE
New Relayer - tsunami.to

### ISSUE THREAD

**Issue by tsunamidev** [tornadocash/tornado-relayer#47]
goerli ens: goerli-v2.tsunamidev.eth
goerli withdrawal:
https://goerli.etherscan.io/tx/0x68a9a43b325569b30007c01756dc3a3a4e10ba0b81cf5627223a7a6d46f916bf

mainnet ens: mainnet-v2.tsunamidev.eth
mainnet withdrawal: https://etherscan.io/tx/0xac7baf593be0966c2ac6ccd122f1079018f3bc82a3e4d974dfb481d326ea96c6

Relayer status page: https://status.tsunami.to

telegram: @tsunamidev

**Comment by tsunamidev** [comment]
@0xZick Is there a reason this relayer was added and I was ignored?
https://github.com/tornadocash/tornado-relayer/issues/63

**Comment by dan1kov** [comment]
Please follow instructions [here](https://docs.tornado.cash/general/how-to-become-a-relayer)
