### ISSUE TITLE
New Relayer: degen-relayer.eth

### ISSUE THREAD

**Issue by BlankerL** [tornadocash/tornado-relayer#50]
Goerli ENS: goerli-v2.degen-relayer.eth ([transaction](https://goerli.etherscan.io/tx/0x07a95d25520d3c2bc3483d928e402171e91a1d3ae8b375d2f912b379f2a5788b))
Mainnet ENS: mainnet-v2.degen-relayer.eth ([transaction](https://etherscan.io/tx/0x3abcef92efb7c63e97be12f0bdd09ad07deaa2d02e7972ac97de447aa5d888ff))

Telegram: @BlankerL

**Comment by dan1kov** [comment]
Please follow instructions [here](https://docs.tornado.cash/general/how-to-become-a-relayer)
