### ISSUE TITLE
MAX_GAS_PRICE seems not working

### ISSUE THREAD

**Issue by BlankerL** [tornadocash/tornado-relayer#52]
Hello, I have deployed a relayer and tried to withdraw from it with a MAX_GAS_PRICE set to 100 GWei, but it seemed not effective when withdrawn and took 267 GWei when sending a transaction from relayer.
[transaction](https://etherscan.io/tx/0x3abcef92efb7c63e97be12f0bdd09ad07deaa2d02e7972ac97de447aa5d888ff)

**Comment by rstormsf** [comment]
Can't reproduce, please provide exact value of `MAX_GAS_PRICE` in your config. Make sure it wasn't set in wei value, it should be
`MAX_GAS_PRICE=100`

**Comment by rstormsf** [comment]
Yeah, it's a bit strange behavior. Basically, it works as intended. `MAX_GAS_PRICE` is not what is absolute max gas each tx should be sent out. It's what is the max gas price value it should set when it's trying to bump gas price. 

I can see how it can confuse relayers, so maybe someone needs to change how it currently works.

**Comment by BlankerL** [comment]
> Yeah, it's a bit strange behavior. Basically, it works as intended. `MAX_GAS_PRICE` is not what is absolute max gas each tx should be sent out. It's what is the max gas price value it should set when it's trying to bump gas price.
> 
> I can see how it can confuse relayers, so maybe someone needs to change how it currently works.

Got you. I did not go through the code, thank you very much for the explanation.

**Comment by BlankerL** [comment]
> Yeah, it's a bit strange behavior. Basically, it works as intended. `MAX_GAS_PRICE` is not what is absolute max gas each tx should be sent out. It's what is the max gas price value it should set when it's trying to bump gas price.
> 
> I can see how it can confuse relayers, so maybe someone needs to change how it currently works.

By the way, could you please help to check my new relayer submission in #50?
