### ISSUE TITLE
New Relayer - mainnet-v2.tornchina.eth

### ISSUE THREAD

**Issue by tornchina** [tornadocash/tornado-relayer#54]
Mainnet
ENS: mainnet-v2.tornchina.eth
URL: https://mainnet.tornchina.com
Example transaction:
https://etherscan.io/tx/0x48356f95a738b28d324af6308b73bac0cde500a1039f93caf22b70d83462f0a5

Goerli
ENS: goerli-v2.tornchina.eth
URL: https://goerli.tornchina.com
Example transaction: https://goerli.etherscan.io/tx/0x8f63f7687b56e8b6f4fed103f592400d1b2865d89566380962a45f0148455505

**Comment by ethermachine** [comment]
We are waiting for months ... will you guys allow new relayers or not?

**Comment by dan1kov** [comment]
Please follow instructions [here](https://docs.tornado.cash/general/how-to-become-a-relayer)
