### ISSUE TITLE
New Relayer (mainnet-v2.smillence.eth)

### ISSUE THREAD

**Issue by Smillence** [tornadocash/tornado-relayer#80]
Hi guys, I just set up a new relayer on AWS.

**Mainnet**
- ENS: mainnet-v2.smillence.eth
- URL: https://mainnet-v2.smillence.xyz/
- Withdrawal transaction: https://etherscan.io/tx/0x7cf32808c2c7480dcbe7de2f2f771b3d45dd2c5d17a65221b029c996f10600b3

**Goerli:**
- ENS: goerli-v2.smillence.eth
- URL: https://goerli-v2.smillence.xyz/
- Withdrawal transaction: https://goerli.etherscan.io/tx/0xba571fc28ce0753ac0969910e232f06d5205f10e78d990ad890a9bef32a14285

Telegram: [@Smillence](https://t.me/Smillence)

**Comment by ethermachine** [comment]
when are you guys releasing the new relayer that is being discussed for almost 1 year?
https://torn.community/t/audit-suggestion-relayer-registry/1838

**Comment by Smillence** [comment]
This is the recent message I got from Gozzy in discord:

> I think it would safe to estimate within the first half of the new year, based on the recent progress on auditing the registry

So my hope is the TC team is gonna release it soon. But I am also not exactly sure so cc @poma @pertsev @0xZick to confirm that 😀

**Comment by dan1kov** [comment]
Please follow instructions [here](https://docs.tornado.cash/general/how-to-become-a-relayer)
