### ISSUE TITLE
Arbitrum ETH Withdrawal “transaction failed: relayer could not sent your tx”” - Please try a different relayer

### ISSUE THREAD

**Issue by SoniCoder** [tornadocash/tornado-relayer#95]
No matter how many times I try and which relayer I choose, still getting the above error.

During withdrawal, it goes to the very end where it shows "Accepted" then finally this error.

I also noticed that the "recent deposit" entry is not present for this deposit in the Tornado Deposit UI perhaps because i switched to ETH network while the deposit transaction was midway. Right now the funds are locked for me!

Any assistance will be appreciated! Thanks!

Note: After using wallet for gas payment, this problem went away

**Comment by dan1kov** [comment]
Fixed in [PR#99](https://github.com/tornadocash/tornado-relayer/pull/99)
