### ISSUE TITLE
Run locally   npm run start gives this error

### ISSUE THREAD

**Issue by NedimRenesalis** [tornadocash/tornado-relayer#98]
<img width="776" alt="Screenshot 2022-04-13 020119" src="https://user-images.githubusercontent.com/19872990/163073737-61826ae0-4f2b-44c0-bb01-768bf3a598a1.png">

Any ideas why? Since all these supposedly missing are in the /src folder.

**Comment by dan1kov** [comment]
@NedimRenesalis Please use **yarn** instead of **npm**. The steps in the manual have been fixed

**Comment by NedimRenesalis** [comment]
I used yarn, then it reported that the relayer has started on port 8000 and then this error pops up

<img width="776" alt="Screenshot 2022-04-13 222838" src="https://user-images.githubusercontent.com/19872990/163266168-cb43bfd4-1cbe-43dd-bb8b-0f539688ea2a.png">

**Comment by NedimRenesalis** [comment]
Do you suggest here a specific node.js version?

**Comment by NedimRenesalis** [comment]
and them this is displayed: 

<img width="916" alt="x" src="https://user-images.githubusercontent.com/19872990/163267196-19a23a0e-3428-4c42-90fb-3cff3880ce8e.png">

**Comment by dan1kov** [comment]
> Do you suggest here a specific node.js version?

The minimum recommended node version is 12

> and them this is displayed:

You must modify the .env file
https://github.com/tornadocash/tornado-relayer/blob/3c5eaa2c4b1fb08fe2b0a025e258cfcfda393b00/README.md?plain=1#L14-L28

Also you do not have redis installed locally

**Comment by NedimRenesalis** [comment]
I managed to get it working with node v12, but there few issues still:

![tornado errors on url](https://user-images.githubusercontent.com/19872990/163655941-0f5e4c8c-baf4-471a-9086-2c9b1f5ba115.png)

## How to fix the last line of the screenshot?

"health":

{"status":"false", **What does this stand for? Is this okay or is this an issue?**

"error":"Private key must be 32 bytes long"}, **What private key? This is in the .env file, but stands for which key?**

"currentQueue":0 **Is this an issue? Or is this okay?**

--------------------------------------------------------------
## ORACLE_RPC_URL

Is this line in the .env file

 - set `ORACLE_RPC_URL` - rpc url for mainnet node for fetching prices(always have to be on mainnet)

the same RPC URL like for

 - set `HTTP_RPC_URL` rpc url for your ethereum node ?

--------------------------------------------------------------
## DNS settings

Are the DNS settings important in  the .env file ? If I already have an IP address?

VIRTUAL_HOST=example.duckdns.org
LETSENCRYPT_HOST=example.duckdns.org

--------------------------------------------------------------
## Price watcher error:

<img width="542" alt="errors tornado" src="https://user-images.githubusercontent.com/19872990/163656262-6c8d26b9-0e59-431a-9aae-4aed9ebe0ab0.png">

How can I fix this?

**Comment by dan1kov** [comment]
> {"status":"false", **What does this stand for? Is this okay or is this an issue?**

Should be "true"

> "error":"Private key must be 32 bytes long"}, **What private key? This is in the .env file, but stands for which key?**

Private key of Ethereum account for transaction processing


> "currentQueue":0 **Is this an issue? Or is this okay?**

This is normal


> Is this line in the .env file
> 
> * set `ORACLE_RPC_URL` - rpc url for mainnet node for fetching prices(always have to be on mainnet)
> 
> the same RPC URL like for
> 
> * set `HTTP_RPC_URL` rpc url for your ethereum node ?

It depends on which network you are trying to raise the relayer. Can be the same if it is Ethereum Mainnet 

> Are the DNS settings important in the .env file ? If I already have an IP address?

These parameters are used for the docker environment, for local environment you can leave them unchanged

> How can I fix this?



> **Also you do not have redis installed locally**

**Comment by NedimRenesalis** [comment]
## Redis

this is my Redis on the digital ocean droplet where I am spinning up the tornado-relayer:

<img width="556" alt="Screenshot 2022-04-16 013530" src="https://user-images.githubusercontent.com/19872990/163858372-485f15cd-2966-4c46-bc73-112bb02a9840.png">

nevertheless, I get this Redis related error in the Redis Parser

<img width="510" alt="result" src="https://user-images.githubusercontent.com/19872990/163866945-01347538-cbe4-4543-a321-28405121ed49.png">

**Comment by dan1kov** [comment]
> this is my Redis on the digital ocean droplet

So you need to change `REDIS_URL` according to your environment. By default connects to the redis server at the address 127.0.0.1 with port 6379:

https://github.com/tornadocash/tornado-relayer/blob/3c5eaa2c4b1fb08fe2b0a025e258cfcfda393b00/.env.example#L6

**Comment by dan1kov** [comment]
> nevertheless, I get this Redis related error in the Redis Parser

Please double-check `ORACLE_RPC_URL`. priceWatcher can't get prices then therefore can't write to redis

**Comment by NedimRenesalis** [comment]
Yes, it was wss instead of https in the ORACLE_RPC_URL

Thank you for your help.

**Comment by NedimRenesalis** [comment]
.

**Comment by NedimRenesalis** [comment]
.
